### PR TITLE
add create_indexes to instll instructions

### PR DESCRIPTION
**Pull request by tyrasd**

### CODE REVIEW

**Review by batpad — APPROVED** [review]

**Comment by batpad** [comment]
@tyrasd I think the reason that might have been skipped there (and why the index creation is in a separate .sql file), is because one might want to create indexes after the import process finishes, so that the imports run a bit faster.

Although, I'm not sure how much of a difference that makes, and we were definitely missing the step to create indexes in the README. Perhaps it is better to add as a note to remember to run after one runs the imports?

**Comment by tyrasd** [comment]
> Perhaps it is better to add as a note to remember to run after one runs the imports?

good point. I've added a sentence that the command can also be delayed. What do you think?

**Comment by batpad** [comment]
Thanks @tyrasd !

If you are attempting to use this, I would be curious to know if it still works - I don't think I've attempted an import with this in a few years now.

@amishas157 @manoharuss - do you know if one of you would be able to merge this simple README update? Thanks!

**Comment by manoharuss** [comment]
Nice thanks @batpad and @tyrasd

**Review by manoharuss — APPROVED** [review]
Thanks!

**Pull request merged**
